name: Keep ChainArena Alive

on:
  schedule:
    - cron: "*/15 * * * *"  # every 15 minutes UTC

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Curl to keep ChainArena alive
        run: curl --silent --show-error https://chainarena.onrender.com/tournaments
